# ----------- CONFIGURABLE START -----------
title:            "LiberXue|FullStack|独立开发者|jekyll blog|GitHub blog"
description:      "Full Stack独立开发者|欢迎来到 LiberXue「角落」侃侃理想、谈谈人生、敲敲代码。"
url:              https://liberxue.github.io # 域名
signoff:          "jinhee0906" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:        jinhee0906
    url:          /
    external:     false
  - name:         jinhee0906
    url:          /book
    external:     false
  - name:         jinhee0906
    url:          /road
    external:     false
  - name:         jinhee0906
    url:          /archives
    external:     false
  - name:         jinhee0906
    url:          /tags
    external:     false
  - name:         jinhee0906
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
